config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
  }
  root "tweets#index"
  resources :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet['user_id'] = current_user.id
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :name)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-fixed-top
  .container
    .clearfix
      .navbar-brand.pull-xs-left= link_to "Couittar", root_path
      %button.navbar-toggler.hidden-sm-up.pull-xs-right{"data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", type: "button"}
        ☰
      #exCollapsingNavbar2.collapse.navbar-toggleable-xs.pull-xs-right
        %ul.nav.navbar-nav
        - if user_signed_in?
          %li.nav-item.nav-link
            .dropdown
              #dropdownMenu1.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
                = current_user.name
              .user-menu.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1"}
                .p-x-1= link_to "プロフィール設定", edit_user_registration_path
                .dropdown-divider
                .p-x-1= link_to "ログアウト", destroy_user_session_path, method: :delete
          %li.nav-item
            %button.btn.btn-sm.btn-primary{"data-target" => "#myModal", "data-toggle" => "modal", type: "button"}
              ツイート
          #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
            .modal-dialog{role: "document"}
              .modal-content
                = form_for(Tweet.new) do |f|
                  .modal-header
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
                      %span{"aria-hidden" => "true"} &times;
                    %h6#myModalLabel.modal-title.text-xs-center ツイートする
                  .modal-body
                    .field
                      = f.text_area :message, class: "form-control", placeholder: "名言を入力してください"
                  .modal-footer
                    = f.submit "投稿する", class: "btn btn-sm btn-primary"
        - else
          %li.nav-item.nav-link
            .dropdown
              #dropdownMenu1.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
                アカウントをお持ちの場合 ログイン
              .signin.dropdown-menu.dropdown-menu-right.p-a-1{"aria-labelledby" => "dropdownMenu1"}
                %small アカウントをお持ちの場合
                = form_for(User.new, url: user_session_path) do |f|
                  .field
                    = f.email_field :email, autofocus: true, class: "form-control", placeholder: "メールアドレス"
                  .field
                    = f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "パスワード"
                  .field
                    = f.check_box :remember_me
                    %small= f.label :remember_me, "保存する"
                  .actions
                    = f.submit "ログイン", class: "btn btn-sm btn-block btn-primary"
                  .dropdown-divider
                  %small Couittarを使ってみよう
                  = link_to "アカウント作成", new_user_registration_path, class: "btn btn-sm btn-block btn-info"

app/views/layouts/_notice.html.haml
- if notice
  .container.alert-wrapper.m-t-1
    .alert.alert-info.alert-dismissible{role: "alert"}
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
        %span{"aria-hidden" => "true"} &times;
      = notice
- elsif alert
  .container.alert-wrapper.m-t-1
    .alert.alert-danger.alert-dismissible{role: "alert"}
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
        %span{"aria-hidden" => "true"} &times;
      = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title Couittar
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/notice'
    = yield

app/views/tweets/_form.html.haml
= form_for(@tweet) do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2
        = pluralize(@tweet.errors.count, "error")
        prohibited this tweet from being saved:
      %ul
        - @tweet.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :message
    %br/
    = f.text_field :message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/tweets/edit.html.haml
%h1 Editing Tweet
= render 'form'
= link_to 'Show', @tweet
|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
.container.p-y-1
  .row
    .col-lg-9.col-lg-push-3
      - if user_signed_in?
        = form_for(@tweet) do |f|
          .field
            = f.text_area :message, class: "form-control", placeholder: "名言を投稿しましょう"
          .actions.text-xs-right
            = f.submit "投稿する", class: "btn btn-sm btn-primary"
      %ul.list-unstyled.tweets
        - @tweets.each do |tweet|
          %li
            .row.tweet
              .col-xs-2.col-md-1
              .col-xs-10.col-md-11
                .clearfix
                  %b.pull-xs-left= tweet.user.name
                  .pull-xs-left.p-l-1= time_ago_in_words(tweet.created_at)
                %p.m-b-0= tweet.message
    .col-lg-3.col-lg-pull-9

  %p#notice= notice
  %h1 Listing Tweets
  = form_for(@tweet) do |f|
    - if @tweet.errors.any?
      #error_explanation
        %h2
          = pluralize(@tweet.errors.count, "error")
          prohibited this tweet from being saved:
        %ul
          - @tweet.errors.full_messages.each do |message|
            %li= message
    .field
      = f.label :message
      %br/
      = f.text_field :message, class: "form-control"
    .actions
      = f.submit "投稿する", class: "btn btn-primary"
  %table
    %thead
      %tr
        %th Message
        %th Name
        %th{:colspan => "3"}
    %tbody
      - @tweets.each do |tweet|
        %tr
          %td= tweet.message
          %td= tweet.name
          %td= link_to 'Show', tweet
          %td= link_to 'Edit', edit_tweet_path(tweet)
          %td= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.haml
%h1 New Tweet
= render 'form'
= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice
%p
  %strong Message:
  = @tweet.message
%p
  %strong Name:
  = @tweet.name
= link_to 'Edit', edit_tweet_path(@tweet)
|
= link_to 'Back', tweets_path

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/